### ISSUE TITLE
Cross Platform Support - Windows line endings formatting

### ISSUE THREAD

**Issue by dgautsch** [sheerun/modern-node#2]
It seems when I run `modern format` on a windows platform it corrects all the line endings. This is mainly an issue when the project is worked on by unix and windows developers. Is there a way around this?

EDIT: This is most likely an issue with prettiers settings. Users will need to make sure they enforce line endings when working cross-platform projects. https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#end_of_line

**Comment by sheerun** [comment]
I think prettier recommends using LF instead of CRLF on Windows and let your editor handle this
