### ISSUE TITLE
Modern Lint Reporting no-fallthrough linting errors incorrectly

### ISSUE THREAD

**Issue by dgautsch** [sheerun/modern-node#3]
In my codebase I have this switch statement

```javascript
switch (error.code) {
    case 'code1':
      doSomething()
      process.exit(1)
    case 'code':
      doSomethingElse()
      process.exit(1)
    default:
      throw error
  }
```
If I run `npx standard` I don't get any linting errors.

If I run `npx prettier-standard --lint` or `npx modern lint` I receive these errors:

```
  44:5  error  Expected a 'break' statement before 'case'     no-fallthrough
  47:5  error  Expected a 'break' statement before 'default'  no-fallthrough
```

I believe this package is using prettier-standard under the hood so I'm not sure where the disconnect is. The process.exit() should satisify the `no-fallthrough` rule.

Here are the relevant package.json versions:

```json
"modern-node": "2.6.0",
"standard": "14.3.1",
```

EDIT: Ok the issue is standard being at 14.3.1. Looks like prettier-standard is using 14.1.0. I guess there was a change in the higher minor versions.

**Comment by dgautsch** [comment]
This was most likely a change in ESLint at some point but I can't pinpoint the change. I've downgraded my local copy of standard to 14.1.0 to match modern-node.

**Comment by sheerun** [comment]
linting is built into prettier-standard, you don't need to use `standard` itself

**Comment by dgautsch** [comment]
Ah ok, good to know, I think I had it installed locally for VSCode. Will VSCode find the right version if it's not installed as a dependency in the project? I can test.

**Comment by sheerun** [comment]
If you're using https://github.com/numso/prettier-standard-vscode then it's not based on prettier-standard but is using prettier and standard separately

**Comment by sheerun** [comment]
Oh wait they switched to prettier-standard actually, then I don't know I'd need to test it
