### ISSUE TITLE
Build and publish tooling

### ISSUE THREAD

**Issue by dnl-brnr** [sheerun/modern-node#5]
@sheerun 

Considering the tagline is:

>All-in-one development toolkit for creating node modules... 

How do you feel about incorporating build/publish tooling, something along the lines of [pack](https://github.com/pikapkg/pack)?

**Comment by sheerun** [comment]
There was one at the very beginning but I've removed it because I felt there is not industry-standard for it yet. Just, Prettier, and Eslint are used by everyone now.

**Comment by sheerun** [comment]
Besides there is no need to build anything before publishing if you just write modern node and use `require` instead of `import`. I feel this is the best practice now.

**Comment by dnl-brnr** [comment]
I see, fair enough. Thanks!
